AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FiatLux Backend - Serverless infrastructure for note processing

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage

  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: Anthropic API key for Claude

  ClerkPublishableKey:
    Type: String
    Description: Clerk publishable key for JWT verification

  ClerkSecretKey:
    Type: String
    NoEcho: true
    Description: Clerk secret key

Globals:
  Function:
    Timeout: 300  # 5 minutes for processing
    MemorySize: 1024
    Environment:
      Variables:
        # Use Sub instead of Ref to avoid circular dependency with ProcessorFunction
        S3_BUCKET: !Sub fiatlux-storage-${Stage}-${AWS::AccountId}
        JOBS_TABLE: !Sub fiatlux-jobs-${Stage}
        PROJECTS_TABLE: !Sub fiatlux-projects-${Stage}
        # Note: AWS_REGION is set automatically by Lambda runtime
        ANTHROPIC_API_KEY: !Ref AnthropicApiKey
        CLERK_PUBLISHABLE_KEY: !Ref ClerkPublishableKey
        CLERK_SECRET_KEY: !Ref ClerkSecretKey

Resources:
  # =============================================================================
  # S3 Bucket for storage
  # =============================================================================
  StorageBucket:
    Type: AWS::S3::Bucket
    DependsOn: ProcessorS3Permission
    Properties:
      BucketName: !Sub fiatlux-storage-${Stage}-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST]
            AllowedOrigins: ['*']
            MaxAge: 3600
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  # Filter for PDFs in project_notes folders
                  # S3 doesn't support wildcards, so we use suffix only
                  # Lambda will filter for /project_notes/ in the path
                  - Name: suffix
                    Value: .pdf
            Function: !GetAtt ProcessorFunction.Arn

  # Permission for S3 to invoke processor Lambda (must be created before bucket)
  ProcessorS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::fiatlux-storage-${Stage}-${AWS::AccountId}
      SourceAccount: !Ref AWS::AccountId

  # =============================================================================
  # DynamoDB Table for job tracking
  # =============================================================================
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub fiatlux-jobs-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-jobs-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # =============================================================================
  # DynamoDB Table for projects (organized by user)
  # =============================================================================
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub fiatlux-projects-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: project_id
          AttributeType: S
        - AttributeName: updated_at
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: project_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: project-lookup-index
          KeySchema:
            - AttributeName: project_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: user-recent-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: updated_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # =============================================================================
  # API Lambda Function
  # =============================================================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fiatlux-api-${Stage}
      Runtime: python3.11
      CodeUri: ../
      Handler: lambda.api_handler.lambda_handler
      Description: FiatLux API endpoints
      Environment:
        Variables:
          PROCESSOR_FUNCTION: !Sub fiatlux-processor-${Stage}
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - S3CrudPolicy:
            BucketName: !Sub fiatlux-storage-${Stage}-${AWS::AccountId}
        - LambdaInvokePolicy:
            FunctionName: !Sub fiatlux-processor-${Stage}
      Events:
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /health
            Method: GET
        SignIn:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /auth/signin
            Method: POST
        AuthRefresh:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /auth/refresh
            Method: POST
        Upload:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /upload
            Method: POST
        SubmitJob:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /jobs
            Method: POST
        GetJob:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /jobs/{job_id}
            Method: GET
        ListJobs:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /jobs
            Method: GET
        Execute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /execute
            Method: POST
        # Project endpoints
        ListProjects:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /projects
            Method: GET
        GetProject:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /projects/{project_id}
            Method: GET
        CreateProject:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /projects
            Method: POST
        UpdateProject:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /projects/{project_id}
            Method: PUT
        DeleteProject:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /projects/{project_id}
            Method: DELETE
        ProjectFiles:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /projects/{project_id}/files
            Method: GET

  # =============================================================================
  # Processor Lambda Function (Docker-based for poppler)
  # =============================================================================
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub fiatlux-processor-${Stage}
      PackageType: Image
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.us-west-1.amazonaws.com/fiatlux-processor:latest
      Description: FiatLux PDF processor with Claude
      Timeout: 900  # 15 minutes for large PDFs
      MemorySize: 2048
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
        - S3CrudPolicy:
            BucketName: !Sub fiatlux-storage-${Stage}-${AWS::AccountId}
    Metadata:
      DockerTag: latest
      DockerContext: ../
      Dockerfile: infra/Dockerfile.processor

  # =============================================================================
  # HTTP API (API Gateway v2)
  # =============================================================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - X-Api-Key
          - Authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${HttpApi}.execute-api.us-west-1.amazonaws.com/${Stage}
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  StorageBucketName:
    Description: S3 bucket name for storage
    Value: !Ref StorageBucket
    Export:
      Name: !Sub ${AWS::StackName}-StorageBucket

  JobsTableName:
    Description: DynamoDB table name for jobs
    Value: !Ref JobsTable
    Export:
      Name: !Sub ${AWS::StackName}-JobsTable

  ProjectsTableName:
    Description: DynamoDB table name for projects
    Value: !Ref ProjectsTable
    Export:
      Name: !Sub ${AWS::StackName}-ProjectsTable

  ApiFunctionArn:
    Description: API Lambda function ARN
    Value: !GetAtt ApiFunction.Arn

  ProcessorFunctionArn:
    Description: Processor Lambda function ARN
    Value: !GetAtt ProcessorFunction.Arn
