from enum import Enum
from dataclasses import dataclass, field
from datetime import datetime


class ProjectStatus(Enum):
    """Status of a project in the pipeline."""
    PENDING = "pending"           # Created but not processed yet
    PROCESSING = "processing"     # Being generated by Claude
    READY = "ready"               # Available for viewing/editing
    FAILED = "failed"             # Generation failed


@dataclass
class Project:
    """
    Represents a generated project.

    Projects are created when a user uploads notes in "Create Project" mode.
    The generated code is stored in S3 at the s3_path location.
    """
    project_id: str                       # UUID (primary key)
    user_id: str                          # Clerk user ID (owner)
    name: str                             # Display name
    s3_path: str                          # Path in S3 bucket (e.g., "projects/user123/my-app/")

    # Optional metadata
    description: str = ""
    status: ProjectStatus = ProjectStatus.PENDING
    source_note_path: str = ""            # Original note that created this project

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        return {
            "project_id": self.project_id,
            "user_id": self.user_id,
            "name": self.name,
            "s3_path": self.s3_path,
            "description": self.description,
            "status": self.status.value,
            "source_note_path": self.source_note_path,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Project":
        return cls(
            project_id=data["project_id"],
            user_id=data["user_id"],
            name=data["name"],
            s3_path=data["s3_path"],
            description=data.get("description", ""),
            status=ProjectStatus(data.get("status", "pending")),
            source_note_path=data.get("source_note_path", ""),
            created_at=datetime.fromisoformat(data["created_at"]),
            updated_at=datetime.fromisoformat(data["updated_at"]),
        )
